name: lego_express
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1                # Variables de entorno
  go_router: ^14.8.0                    # Manejo de rutas
  flutter_riverpod: ^2.6.1              # Manejo de estados - específicos
  lottie: ^3.3.1                        # Animaciones - lottie
  loading_animation_widget: ^1.3.0      # Animaciones - loading
  flutter_staggered_grid_view: ^0.7.0   # Grid con desfase
  logger: ^2.5.0                        # Mejores prints
  firebase_core: ^3.11.0                # Firebase - Configuracion
  firebase_auth: ^5.4.2                 # Firebase - Autenticación
  flutter_spinkit: ^5.2.1               # Animaciones de carga
  path_provider: ^2.1.5                 # Rutas internas
  sqflite: ^2.4.1                       # SQL DB
  dio: ^5.8.0+1                         # Request
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/icon/
    - assets/images/
    - assets/gifs/
    - assets/images/icons/
    - assets/images/categories/
    - assets/animations/
    - assets/animations/lottie/
    - assets/fonts/
    - .env



  fonts:
    - family: Catamaran
      fonts:
        - asset: assets/fonts/catamaran/Catamaran-Thin.ttf
          weight: 100
        - asset: assets/fonts/catamaran/Catamaran-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/catamaran/Catamaran-Light.ttf
          weight: 300
        - asset: assets/fonts/catamaran/Catamaran-Regular.ttf
          weight: 400
        - asset: assets/fonts/catamaran/Catamaran-Medium.ttf
          weight: 500
        - asset: assets/fonts/catamaran/Catamaran-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/catamaran/Catamaran-Bold.ttf
          weight: 700
        - asset: assets/fonts/catamaran/Catamaran-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/catamaran/Catamaran-Black.ttf
          weight: 900
